package e3i2.ecommerce_backoffice.common.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import static e3i2.ecommerce_backoffice.common.util.Constants.*;

@Getter
public enum ErrorEnum {
    ERR_NOT_ADMIN_STATUS_WAIT(HttpStatus.CONFLICT, MSG_ADMIN_STATUS_NOT_WAIT)
    , ERR_LOGOUT_DUPLICATED(HttpStatus.UNAUTHORIZED, MSG_LOGOUT_DUPLICATED)
    , ERR_NOT_LOGIN_ACCESS(HttpStatus.UNAUTHORIZED, MSG_NOT_LOGIN_ACCESS)
    , ERR_NOT_FOUND_CUSTOMER(HttpStatus.NOT_FOUND, MSG_NOT_FOUND_CUSTOMER)
    , ERR_DUPLICATED_EMAIL(HttpStatus.CONFLICT, MSG_DUPLICATED_EMAIL)
    , ERR_DUPLICATED_PHONE(HttpStatus.CONFLICT, MSG_DUPLICATED_PHONE)
    , ERR_WRONG_EMAIL_PASSWORD(HttpStatus.BAD_REQUEST, MSG_WRONG_EMAIL_PASSWORD)
    , ERR_WAIT_ADMIN_ACCOUNT_LOGIN(HttpStatus.FORBIDDEN, MSG_WAIT_ADMIN_ACCOUNT_LOGIN)
    , ERR_DENY_ADMIN_ACCOUNT_LOGIN(HttpStatus.FORBIDDEN, MSG_DENY_ADMIN_ACCOUNT_LOGIN)
    , ERR_SUSPEND_ADMIN_ACCOUNT_LOGIN(HttpStatus.FORBIDDEN, MSG_SUSPEND_ADMIN_ACCOUNT_LOGIN)
    , ERR_IN_ACT_ADMIN_ACCOUNT_LOGIN(HttpStatus.FORBIDDEN, MSG_IN_ACT_ADMIN_ACCOUNT_LOGIN)
    , ERR_UNAUTHORIZED_ACCOUNT_LOGIN(HttpStatus.FORBIDDEN, MSG_UNAUTHORIZED_ACCOUNT_LOGIN)
    , ERR_ONLY_SUPER_ADMIN_ACCESS(HttpStatus.FORBIDDEN, MSG_ONLY_SUPER_ADMIN_ACCESS)
    , ERR_NOT_FOUND_ADMIN(HttpStatus.NOT_FOUND, MSG_NOT_FOUND_ADMIN)
    , ERR_NOT_FOUND_ADMIN_ROLE(HttpStatus.BAD_REQUEST, MSG_NOT_FOUND_ADMIN_ROLE_ERR)
    , ERR_NOT_FOUND_ADMIN_STATUS(HttpStatus.BAD_REQUEST, MSG_NOT_FOUND_ADMIN_STATUS_ERR)
    , ERR_NOT_FOUND_PRODUCT(HttpStatus.NOT_FOUND, MSG_NOT_FOUND_PRODUCT)
    , ERR_NOT_FOUND_PRODUCT_CATEGORY(HttpStatus.BAD_REQUEST, MSG_NOT_FOUND_PRODUCT_CATEGORY_ERR)
    , ERR_NOT_FOUND_PRODUCT_STATUS(HttpStatus.BAD_REQUEST, MSG_NOT_FOUND_PRODUCT_STATUS_ERR)
    , ERR_DELETED_ADMIN_SELF(HttpStatus.FORBIDDEN, MSG_NOT_DELETE_ADMIN_SELF)
    , ERR_SAME_OLD_PASSWORD(HttpStatus.BAD_REQUEST, MSG_SAME_OLD_PASSWORD)
    , ERR_NOT_MATCH_PASSWORD(HttpStatus.BAD_REQUEST, MSG_NOT_MATCH_PASSWORD)
    , ERR_DENY_CUSTOMER_ACCOUNT_DELETE(HttpStatus.BAD_REQUEST, MSG_DENY_CUSTOMER_ACCOUNT_DELETE)
    , ERR_NOT_FOUND_CUSTOMER_STATUS(HttpStatus.BAD_REQUEST, MSG_NOT_FOUND_CUSTOMER_STATUS_ERR)
    , ERR_ORDER_TO_DISCONTINUE(HttpStatus.BAD_REQUEST, MSG_ORDER_TO_DISCONTINUE_ERR)
    , ERR_ORDER_TO_SOLD_OUT(HttpStatus.BAD_REQUEST, MSG_ORDER_TO_SOLD_OUT_ERR)
    , ERR_ORDER_TO_QUANTITY_OVER(HttpStatus.BAD_REQUEST, MSG_ORDER_TO_QUANTITY_OVER_ERR)
    , ERR_NOT_FOUND_ORDER(HttpStatus.NOT_FOUND, MSG_NOT_FOUND_ORDER)
    , ERR_NOT_FOUND_ORDER_STATUS(HttpStatus.BAD_REQUEST, MSG_NOT_FOUND_ORDER_STATUS_ERR)
    , ERR_ORDER_PROCESSING_DELIVERED_FORBIDDEN(HttpStatus.FORBIDDEN, MSG_ORDER_PROCESSING_DELIVERED_FORBIDDEN)
    , ERR_ORDER_STATUS_INVALID_TRANSITION(HttpStatus.BAD_REQUEST, MSG_ORDER_STATUS_INVALID_TRANSITION)
    , ERR_ORDER_ALREADY_CANCELLED(HttpStatus.BAD_REQUEST, MSG_ORDER_ALREADY_CANCELLED)
    , ERR_NOT_FOUND_REVIEW(HttpStatus.NOT_FOUND, MSG_NOT_FOUND_REVIEW);

    private final HttpStatus status;
    private final String message;

    ErrorEnum(HttpStatus status, String message) {
        this.status = status;
        this.message = message;
    }
}
